# Generated by Django 4.2.8 on 2023-12-26 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rssapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='article',
            table='articles',
        ),
    ]
