# Generated by Django 4.2.8 on 2023-12-27 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rssapp', '0002_alter_article_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='source_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
