# Generated by Django 4.2.8 on 2024-01-04 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rssapp', '0003_article_author_article_source_url'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['score', 'publication_date', 'id'], name='score_pubdate_id_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['publication_date', 'id'], name='pubdate_id_idx'),
        ),
    ]
