// /home/pkimani/getting-started-app/djrssproj-next/app/layout.js

import { useTheme } from '../components/themeContext';
import '../styles/globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  const { theme } = useTheme(); // Use the theme from the context

  return (
    <div className={theme}> {/* Apply the theme class to the root div */}
      {children}
    </div>
  );
}